In [3]:
%load_ext sql
%sql sqlite:///followers.db

/Users/vanessafriedemann/Library/Python/2.7/lib/python/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/Users/vanessafriedemann/Library/Python/2.7/lib/python/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")

u'Connected: None@followers.db'

In [4]:
influencer = '@NASA'
filename = 'influencer_' + influencer.replace('@','') +'.txt'

with open(filename,'r') as f_in:
    for line in f_in: 
        line = line.rstrip()
        pieces = line.split(' ')
        id = pieces[3].split('=')[1]
        following = int(pieces[4].split('=')[1] == 'True')
        print id,following
        try: 
            %sql INSERT INTO Influencers (FollowerID, InfluencerName, Following) VALUES (:id, :influencer, :following);
        except:
            print 'failed'
            continue

458977683 0
1 rows affected.
4197454515 0
1 rows affected.
93080767 0
1 rows affected.
4222265832 0
1 rows affected.
3249250893 0
1 rows affected.
1476964476 0
1 rows affected.
91756612 0
1 rows affected.
3023825365 0
1 rows affected.
456993297 0
1 rows affected.
1516949503 0
1 rows affected.
3040277234 0
1 rows affected.
328945115 0
1 rows affected.
4225191558 0
1 rows affected.
3876653366 0
1 rows affected.
3606495681 0
1 rows affected.
1382421882 0
1 rows affected.
3374935769 0
1 rows affected.
920129395 0
1 rows affected.
4237032380 0
1 rows affected.
4179362663 0
1 rows affected.
4138184261 0
1 rows affected.
4179161021 0
1 rows affected.
3310100678 0
1 rows affected.
183222594 0
1 rows affected.
784948694 0
1 rows affected.
3241428076 0
1 rows affected.
3246523285 0
1 rows affected.
248299802 1
1 rows affected.
483018613 0
1 rows affected.
4186318205 0
1 rows affected.
4174817968 0
1 rows affected.
227076818 0
1 rows affected.
4243774224 0
1 rows affected.
2651151645 0
1 rows affected.
4091852261 1
1 rows affected.
634991244 0
1 rows affected.
3020546543 0
1 rows affected.
4247544914 0
1 rows affected.
2722079763 0
1 rows affected.
340204482 0
1 rows affected.
4144695913 0
1 rows affected.
4252246754 0
1 rows affected.
4182468075 1
1 rows affected.
4188251615 0
1 rows affected.
2895008530 0
1 rows affected.
2970946769 0
1 rows affected.
4112017894 0
1 rows affected.
2762060114 0
1 rows affected.
987253513 0
1 rows affected.
25166654 0
1 rows affected.
4117253957 0
1 rows affected.
469443065 0
1 rows affected.
1895391001 0
1 rows affected.
3370263671 0
1 rows affected.
552335339 0
1 rows affected.
3315764610 1
1 rows affected.
4227049038 0
1 rows affected.
2447663646 0
1 rows affected.
4064100853 0
1 rows affected.
98164653 0
1 rows affected.
442698573 0
1 rows affected.
2738228891 0
1 rows affected.
4189405599 0
1 rows affected.
4061740283 0
1 rows affected.
2205566808 0
1 rows affected.
4190356817 1
1 rows affected.
4221651678 0
1 rows affected.
3304688003 1
1 rows affected.
4244852353 0
1 rows affected.
4229509879 0
1 rows affected.
1588213088 0
1 rows affected.
4195249959 0
1 rows affected.
4191256816 0
1 rows affected.
464724621 0
1 rows affected.
2741393619 0
1 rows affected.
4243717759 0
1 rows affected.
4221884234 0
1 rows affected.
4239861793 0
1 rows affected.
321791742 0
1 rows affected.
2582884699 0
1 rows affected.
3311723834 1
1 rows affected.
2262581096 1
1 rows affected.
281884573 0
1 rows affected.
4235411480 0
1 rows affected.
3968289433 0
1 rows affected.
3370682969 0
1 rows affected.
3740162602 0
1 rows affected.
3232600340 0
1 rows affected.
4120953335 0
1 rows affected.
4120772555 0
1 rows affected.
2852092655 0
1 rows affected.
3280889948 1
1 rows affected.
2400657192 0
1 rows affected.
4179429081 0
1 rows affected.
570523162 0
1 rows affected.
2863139113 0
1 rows affected.
94086966 0
1 rows affected.
3339694847 0
1 rows affected.
1029649357 0
1 rows affected.
4062200885 0
1 rows affected.
38372491 0
1 rows affected.
2794021615 0
1 rows affected.
4174435272 0
1 rows affected.
488835339 1
1 rows affected.
4197192334 0
1 rows affected.
2769495250 0
1 rows affected.
4235534532 0
1 rows affected.
3503062762 0
1 rows affected.
541405093 0
1 rows affected.
4098498083 0
1 rows affected.
125922787 0
1 rows affected.
1167337332 0
1 rows affected.
4241013014 0
1 rows affected.
4026130756 1
1 rows affected.
3917318178 0
1 rows affected.
2600990851 0
1 rows affected.
3322722203 0
1 rows affected.
2803040318 0
1 rows affected.
2296731886 0
1 rows affected.
2373680170 0
1 rows affected.
4243215854 0
1 rows affected.
4195183162 0
1 rows affected.
131703129 0
1 rows affected.
4148516722 0
1 rows affected.
3785362760 0
1 rows affected.
4194237561 0
1 rows affected.
2367943817 0
1 rows affected.
54995278 1
1 rows affected.
3259526558 0
1 rows affected.
4193028081 0
1 rows affected.
4112513818 0
1 rows affected.
3016675659 0
1 rows affected.
3612940877 0
1 rows affected.
2739220490 0
1 rows affected.
450315857 1
1 rows affected.
4137621459 0
1 rows affected.
3084505881 1
1 rows affected.
3312305696 0
1 rows affected.
188109811 1
1 rows affected.
4252280112 0
1 rows affected.
2715874511 0
1 rows affected.
2153913853 0
1 rows affected.
1594449770 0
1 rows affected.
2855759767 0
1 rows affected.
2886273986 0
1 rows affected.
65147082 0
1 rows affected.
486700208 0
1 rows affected.
2228653821 0
1 rows affected.
4245352579 0
1 rows affected.
2883327183 0
1 rows affected.
2901545803 0
1 rows affected.
3433180156 0
1 rows affected.
4086612012 0
1 rows affected.
1152809226 0
1 rows affected.
4197094834 0
1 rows affected.
4196024057 0
1 rows affected.
3296423924 0
1 rows affected.
3396912945 0
1 rows affected.
4235827465 0
1 rows affected.
4182949653 0
1 rows affected.
4180526789 0
1 rows affected.
4182278001 0
1 rows affected.
3783591436 0
1 rows affected.
4221493932 0
1 rows affected.
2904526355 0
1 rows affected.
2745845051 0
1 rows affected.
1345739341 0
1 rows affected.
3273365557 0
1 rows affected.
597904905 0
1 rows affected.
4248607694 0
1 rows affected.
1280792756 1
1 rows affected.
2904609322 0
1 rows affected.
83802935 0
1 rows affected.
3544568954 0
1 rows affected.
4192915307 0
1 rows affected.
3194234851 0
1 rows affected.
4140872293 1
1 rows affected.
2418060379 0
1 rows affected.
4243532773 1
1 rows affected.
3129434243 0
1 rows affected.
2328066923 0
1 rows affected.
2807688689 0
1 rows affected.
4240422914 0
1 rows affected.
296104091 0
1 rows affected.
1163087000 0
1 rows affected.
89246015 0
1 rows affected.
4237724773 0
1 rows affected.
4197261094 0
1 rows affected.
4188359897 0
1 rows affected.
1459705387 0
1 rows affected.
4195652015 0
1 rows affected.
4249776972 0
1 rows affected.
1147134842 0
1 rows affected.
3327036977 0
1 rows affected.
2316397298 0
1 rows affected.
3897436342 0
1 rows affected.
410275207 0
1 rows affected.
4165751535 0
1 rows affected.
356725592 0
1 rows affected.
4173929980 0
1 rows affected.
2868809288 0
1 rows affected.
4173780538 0
1 rows affected.
4225125974 0
1 rows affected.
3094395474 0
1 rows affected.
4188752068 0
1 rows affected.
2980046727 0
1 rows affected.
4189016422 0
1 rows affected.
4230730946 0
1 rows affected.
477144363 0
1 rows affected.
3111662510 0
1 rows affected.
2285909244 0
1 rows affected.
2726740136 0
1 rows affected.
2781204110 0
1 rows affected.
4025072717 0
1 rows affected.
3247807266 0
1 rows affected.
4216301658 0
1 rows affected.
3625678217 1
1 rows affected.
4174761316 0
1 rows affected.
4151028179 0
1 rows affected.
4182397162 0
1 rows affected.
3421524587 0
1 rows affected.
4189208242 0
1 rows affected.
116489865 0
1 rows affected.
4170924413 0
1 rows affected.
4173208757 0
1 rows affected.
1879546500 0
1 rows affected.
4198072955 0
1 rows affected.
4229974993 0
1 rows affected.
3040546657 0
1 rows affected.
3327797629 0
1 rows affected.
4235121559 0
1 rows affected.
4184727082 0
1 rows affected.
4004214202 0
1 rows affected.
4115172674 0
1 rows affected.
824392536 0
1 rows affected.
4194919726 0
1 rows affected.
4185842591 0
1 rows affected.
4174609995 1
1 rows affected.
33688666 0
1 rows affected.
4215532278 0
1 rows affected.
4178687140 1
1 rows affected.
4122637468 0
1 rows affected.
3376006204 0
1 rows affected.
2986056446 0
1 rows affected.
4090286019 0
1 rows affected.
208823340 0
1 rows affected.
4251608114 0
1 rows affected.
2942418140 0
1 rows affected.
4079076935 0
1 rows affected.
760164763 0
1 rows affected.
4090821665 0
1 rows affected.
2480564254 0
1 rows affected.
621335465 0
1 rows affected.
3384181911 0
1 rows affected.
4240489999 0
1 rows affected.
3497569453 0
1 rows affected.
3303674242 0
1 rows affected.
4162804093 0
1 rows affected.
4055856136 0
1 rows affected.
3303553308 0
1 rows affected.
4186785803 0
1 rows affected.
3377938756 0
1 rows affected.
3005605980 0
1 rows affected.
2779869837 0
1 rows affected.
4184749967 1
1 rows affected.
2995638549 0
1 rows affected.
2664836932 0
1 rows affected.
4228151174 0
1 rows affected.
1108103858 1
1 rows affected.
3361558006 0
1 rows affected.
2432755752 0
1 rows affected.
1687191703 0
1 rows affected.
312454826 0
1 rows affected.
226433563 0
1 rows affected.
2937327865 0
1 rows affected.
2412534782 0
1 rows affected.
4222092499 0
1 rows affected.
70094756 0
1 rows affected.
2958573961 0
1 rows affected.
4193951013 0
1 rows affected.
1621948675 0
1 rows affected.
3199225845 0
1 rows affected.
4230573258 0
1 rows affected.
267998755 0
1 rows affected.
3572179575 0
1 rows affected.
357662574 1
1 rows affected.
4197374668 0
1 rows affected.
3741873633 0
1 rows affected.
3986373433 0
1 rows affected.
2842660149 0
1 rows affected.
3274099332 0
1 rows affected.
3433927895 0
1 rows affected.
168472452 0
1 rows affected.
3419090660 0
1 rows affected.
4186693665 0
1 rows affected.
307571034 0
1 rows affected.
4197188242 0
1 rows affected.
2823753647 0
1 rows affected.
3394867454 0
1 rows affected.
4193254233 0
1 rows affected.
4164997455 0
1 rows affected.
2198283801 0
1 rows affected.
3748105993 0
1 rows affected.
2342366659 0
1 rows affected.
4120908316 0
1 rows affected.
4245877574 0
1 rows affected.
3916403727 0
1 rows affected.
4106625496 0
1 rows affected.
4219226299 0
1 rows affected.
4148290409 0
1 rows affected.
27650769 0
1 rows affected.
4156850259 0
1 rows affected.
4251714138 0
1 rows affected.
4153756943 0
1 rows affected.
3242518541 0
1 rows affected.
2757720298 1
1 rows affected.
1487989800 0
1 rows affected.
4188904701 0
1 rows affected.
4240511772 0
1 rows affected.
3158212594 0
1 rows affected.
1854074719 0
1 rows affected.
4195932675 0
1 rows affected.
2754376491 1
1 rows affected.
4147006786 0
1 rows affected.
4199212048 0
1 rows affected.
4121309775 0
1 rows affected.
446040653 0
1 rows affected.
3921783460 0
1 rows affected.
4222950972 0
1 rows affected.
4230894193 0
1 rows affected.
4236083232 0
1 rows affected.
4246187592 0
1 rows affected.
787402734 0
1 rows affected.
4226285780 1
1 rows affected.
614673339 1
1 rows affected.
3670039456 0
1 rows affected.
4167177315 0
1 rows affected.
4235149453 0
1 rows affected.
536129625 0
1 rows affected.
4244105052 0
1 rows affected.
3293605855 0
1 rows affected.
4235698152 0
1 rows affected.
2456852406 0
1 rows affected.
4188103487 0
1 rows affected.
2885016604 0
1 rows affected.
878381700 0
1 rows affected.
2870753379 0
1 rows affected.
4187572161 0
1 rows affected.
4205589073 0
1 rows affected.
3074158452 0
1 rows affected.
281849924 0
1 rows affected.
4088411158 0
1 rows affected.
3960068241 0
1 rows affected.
1394683742 0
1 rows affected.
1100544739 0
1 rows affected.
4146938177 0
1 rows affected.
3116613352 0
1 rows affected.
2866307939 0
1 rows affected.
116932028 0
1 rows affected.
2761423838 1
1 rows affected.
4187536180 0
1 rows affected.
351435386 0
1 rows affected.
4184380695 0
1 rows affected.
4224107539 0
1 rows affected.
4194698353 0
1 rows affected.
256749437 0
1 rows affected.
824571398 0
1 rows affected.
372756980 0
1 rows affected.
3238067839 0
1 rows affected.
313126113 0
1 rows affected.
4023446470 0
1 rows affected.
504737852 0
1 rows affected.
4227678013 0
1 rows affected.
1592904829 0
1 rows affected.
25903289 0
1 rows affected.
4190687062 0
1 rows affected.
2740104988 1
1 rows affected.
3313221258 1
1 rows affected.
4175661735 0
1 rows affected.
42873508 0
1 rows affected.
2970378317 0
1 rows affected.
350822210 0
1 rows affected.
4173761879 0
1 rows affected.
4224918734 0
1 rows affected.
4184882625 0
1 rows affected.
144277039 0
1 rows affected.
2912690458 0
1 rows affected.
4246574778 0
1 rows affected.
2962830309 0
1 rows affected.
4233895274 0
1 rows affected.
416764734 0
1 rows affected.
4038699016 1
1 rows affected.
4157971894 1
1 rows affected.
3917257453 0
1 rows affected.
4248990432 0
1 rows affected.
4074531255 0
1 rows affected.
1129635740 1
1 rows affected.
4157376192 0
1 rows affected.
3698657659 0
1 rows affected.
3418745057 0
1 rows affected.
4241087894 0
1 rows affected.
4243623013 1
1 rows affected.
4252038673 0
1 rows affected.
3042263154 0
1 rows affected.
4186969954 0
1 rows affected.
3319381147 0
1 rows affected.
3305557550 0
1 rows affected.
4193760557 0
1 rows affected.
3006302093 0
1 rows affected.
208315150 0
1 rows affected.
3342916972 0
1 rows affected.
254441681 0
1 rows affected.
3563120296 0
1 rows affected.
4195023809 0
1 rows affected.
4133994194 0
1 rows affected.
2461873302 1
1 rows affected.
1664362832 1
1 rows affected.
3837748277 0
1 rows affected.
4163760749 0
1 rows affected.
842067787 0
1 rows affected.
4223898746 0
1 rows affected.
2197665606 0
1 rows affected.
4185139889 0
1 rows affected.
3229875649 0
1 rows affected.
3866724975 0
1 rows affected.
4233638472 0
1 rows affected.
3674992102 0
1 rows affected.
2389902864 0
1 rows affected.
4229264294 0
1 rows affected.
3279107869 0
1 rows affected.
374058810 1
1 rows affected.
3167569626 0
1 rows affected.
4181561795 0
1 rows affected.
2364855083 0
1 rows affected.
4190372416 0
1 rows affected.
2746943896 0
1 rows affected.
2752292213 0
1 rows affected.
3290489435 0
1 rows affected.
2636951568 0
1 rows affected.
4074365960 0
1 rows affected.
342464942 0
1 rows affected.
3325975356 0
1 rows affected.
4154944005 0
1 rows affected.
4217053753 0
1 rows affected.
4212560174 1
1 rows affected.
72632944 1
1 rows affected.
2972429175 0
1 rows affected.
110097211 0
1 rows affected.
3775225887 1
1 rows affected.
242209107 0
1 rows affected.
2514208627 0
1 rows affected.
4242494300 0
1 rows affected.
2430594187 1
1 rows affected.
391526145 0
1 rows affected.
3773098516 0
1 rows affected.
4237788492 0
1 rows affected.
3310000191 0
1 rows affected.
85934808 0
1 rows affected.
3339433163 0
1 rows affected.
3344962335 0
1 rows affected.
4189614313 0
1 rows affected.
4180747347 0
1 rows affected.
4189002143 0
1 rows affected.
288533680 0
1 rows affected.
4204310893 0
1 rows affected.
4155996744 0
1 rows affected.
538606586 0
1 rows affected.
4123266149 0
1 rows affected.
4217811020 0
1 rows affected.
4173697707 0
1 rows affected.
4166019614 0
1 rows affected.
975729830 1
1 rows affected.
81687420 0
1 rows affected.
3784421717 0
1 rows affected.
4191803182 0
1 rows affected.
2559593274 0
1 rows affected.
1715334788 1
1 rows affected.
2536047575 0
1 rows affected.
4236545234 0
1 rows affected.
4230371899 0
1 rows affected.
393916016 0
1 rows affected.
4229756832 0
1 rows affected.
4085968042 0
1 rows affected.
3893528237 1
1 rows affected.
4069320315 0
1 rows affected.
3416457839 0
1 rows affected.
37121098 0
1 rows affected.
1717419427 0
1 rows affected.
4186533123 0
1 rows affected.
2592585740 0
1 rows affected.
3363389794 0
1 rows affected.
2255373149 0
1 rows affected.
4150057252 0
1 rows affected.
1338887696 0
1 rows affected.
15823891 1
1 rows affected.
53480186 0
1 rows affected.
4193748047 0
1 rows affected.
44421379 0
1 rows affected.
4056925515 0
1 rows affected.
4193501344 0
1 rows affected.
4128443472 0
1 rows affected.
1161820135 0
1 rows affected.
1912989000 0
1 rows affected.
3845642727 0
1 rows affected.
4243185674 0
1 rows affected.
4182905476 0
1 rows affected.
466060293 1
1 rows affected.
74306758 0
1 rows affected.
4167878781 0
1 rows affected.
1069188241 0
1 rows affected.
242094991 0
1 rows affected.
415741052 0
1 rows affected.
4187414379 0
1 rows affected.
4175987177 0
1 rows affected.
4189722797 1
1 rows affected.
2979360429 0
1 rows affected.
3129392757 0
1 rows affected.
4145510776 0
1 rows affected.
4187726074 0
1 rows affected.
4194298995 0
1 rows affected.
3392555117 0
1 rows affected.
252394125 0
1 rows affected.
4185597083 1
1 rows affected.
4188287513 0
1 rows affected.
4174136291 0
1 rows affected.
4228359313 0
1 rows affected.
4188205983 0
1 rows affected.
534866009 0
1 rows affected.
4225803798 0
1 rows affected.
4218450385 0
1 rows affected.
3221576102 0
1 rows affected.
125473782 1
1 rows affected.
4237222153 0
1 rows affected.
2417563729 0
1 rows affected.
4234563674 0
1 rows affected.
773846593 0
1 rows affected.
4243076414 0
1 rows affected.
4242136814 0
1 rows affected.
2807370135 0
1 rows affected.
2860969157 0
1 rows affected.
363364728 0
1 rows affected.
3299450623 0
1 rows affected.
2909169000 0
1 rows affected.
4184818361 0
1 rows affected.
3547191254 0
1 rows affected.
3885135733 0
1 rows affected.
391057218 0
1 rows affected.
4180980628 0
1 rows affected.
4177783397 0
1 rows affected.
4252691293 0
1 rows affected.
3023730215 0
1 rows affected.
4166276477 0
1 rows affected.
3907344164 0
1 rows affected.
4178391279 1
1 rows affected.
500957536 0
1 rows affected.
226745334 1
1 rows affected.
597299884 0
1 rows affected.
2468217834 0
1 rows affected.
1975926385 0
1 rows affected.
2965412317 0
1 rows affected.
2333903971 0
1 rows affected.
1967784732 0
1 rows affected.
822458581 0
1 rows affected.
3734334922 1
1 rows affected.
3317433966 1
1 rows affected.
3176975377 0
1 rows affected.
3175636182 0
1 rows affected.
3430674130 0
1 rows affected.
3756399432 0
1 rows affected.
1335457622 1
1 rows affected.
4242271278 0
1 rows affected.
602780618 0
1 rows affected.
3252738215 0
1 rows affected.
958841642 0
1 rows affected.
4181385448 0
1 rows affected.
3492618675 0
1 rows affected.
2506739533 0
1 rows affected.
4111969934 0
1 rows affected.
3383365726 0
1 rows affected.
2365623649 0
1 rows affected.
2986313562 0
1 rows affected.
3968010552 0
1 rows affected.
4187313323 0
1 rows affected.
2604201510 0
1 rows affected.
4235704938 0
1 rows affected.
2611874946 1
1 rows affected.
4064877496 0
1 rows affected.
4188523858 0
1 rows affected.
4152152063 0
1 rows affected.
4183961169 0
1 rows affected.
4242310513 0
1 rows affected.
4220501172 0
1 rows affected.
582692428 1
1 rows affected.
3118277381 0
1 rows affected.
4252408160 0
1 rows affected.
4158586389 0
1 rows affected.
4185143652 0
1 rows affected.
4098965337 0
1 rows affected.
3381007143 0
1 rows affected.
4187007141 0
1 rows affected.
4054881015 0
1 rows affected.
1218043278 0
1 rows affected.
16354653 0
1 rows affected.
4069699096 0
1 rows affected.
1106074220 0
1 rows affected.
2309158544 0
1 rows affected.
3413881005 0
1 rows affected.
772223190 1
1 rows affected.
14305604 0
1 rows affected.
4186751298 0
1 rows affected.
2890225408 0
1 rows affected.
4119328487 0
1 rows affected.
3167698821 0
1 rows affected.
3367132317 1
1 rows affected.
2940347215 0
1 rows affected.
4159475473 0
1 rows affected.
4179064874 0
1 rows affected.
3384262175 0
1 rows affected.
3244725057 0
1 rows affected.
2865405551 0
1 rows affected.
2274342962 1
1 rows affected.
4233835752 0
1 rows affected.
4249302913 0
1 rows affected.
4175216829 0
1 rows affected.
2853462612 1
1 rows affected.
3592837692 0
1 rows affected.
2934776731 0
1 rows affected.
4228885700 0
1 rows affected.
2674100912 0
1 rows affected.
3007428481 0
1 rows affected.
782505416 0
1 rows affected.
4185377806 0
1 rows affected.
3744783916 0
1 rows affected.
3181444845 0
1 rows affected.
3981124115 0
1 rows affected.
3304187535 0
1 rows affected.
2795810654 0
1 rows affected.
4167508727 0
1 rows affected.
4158772336 0
1 rows affected.
2413551532 0
1 rows affected.
4183884927 0
1 rows affected.
44653237 0
1 rows affected.
3369752452 1
1 rows affected.
1687624496 0
1 rows affected.
4181592868 0
1 rows affected.
273029437 0
1 rows affected.
3995214370 0
1 rows affected.
4229164340 1
1 rows affected.
4223433913 0
1 rows affected.
3004293036 0
1 rows affected.
276748240 0
1 rows affected.
218978820 0
1 rows affected.
368763386 1
1 rows affected.
3360149770 0
1 rows affected.
4187840483 0
1 rows affected.
4185500961 0
1 rows affected.
4240707314 0
1 rows affected.
4198181658 0
1 rows affected.
3249575180 0
1 rows affected.
4181978428 1
1 rows affected.
4228234878 0
1 rows affected.
3988252161 0
1 rows affected.
2414675609 0
1 rows affected.
3530249475 1
1 rows affected.
463331898 0
1 rows affected.
2781469941 0
1 rows affected.
4228401926 0
1 rows affected.
2222825318 1
1 rows affected.
124943279 1
1 rows affected.
4158530044 0
1 rows affected.
4188880633 0
1 rows affected.
1676003005 0